[package]
name = "common"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
One = { local = "../../../../crates/sui-framework/packages/one-framework" }

[addresses]
common = "0x25726c350b62a0ae218ae3631053a8dac72642e68ad09b046ab39eab634cd8f2"
