name: Trigger builds for images and binaries

on:
  workflow_dispatch:
  push:
    branches: 
      - 'devnet'
      - 'testnet'
      - 'mainnet'
      - 'releases/sui-*-release'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docker-images:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'sui-graphql-rpc') }}
    steps:
      - name: Dispatch Docker Builds in MystenLabs/sui-operations
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # pin@v4.0.1
        with: 
          repository: MystenLabs/sui-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: build-docker-images
          client-payload: '{"sui_commit": "${{ github.sha }}", "docker_hub_tag": "${{ github.ref }}"}'

  release-binaries:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'sui-graphql-rpc') }}
    steps:
      - name: Dispatch Release binaries builds in MystenLabs/sui-operations
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # pin@v4.0.1
        with:
          repository: MystenLabs/sui-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: build-release-binaries
          client-payload: '{"sui_commit": "${{ github.sha }}"}'

  graphql-artifacts:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'sui-graphql-rpc') }}
    steps:
      - name: Dispatch GraphQl artifact builds in MystenLabs/sui-operations
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # pin@v4.0.1
        with:
          repository: MystenLabs/sui-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: build-graphql-artifacts
          client-payload: '{"sui_commit": "${{ github.sha }}", "docker_hub_tag": "${{ github.ref }}"}'
